### ISSUE TITLE
Building the project fails

### ISSUE THREAD

**Issue by maekclena** [freaktechnik/justintv-stream-notifications#320]
I am having problems building the project, `npm run build` cannot find the transifex configuration file. Is it maybe related to [this](https://github.com/freaktechnik/transifex-loader/issues/38)?

## System Info

 - *Operating System*: Arch Linux 4.12.8

## Debug Dump

Result of running `webpack --display errors-only --display-error-details` from the project's directory :

```
ERROR in ./_locales/de/messages.json
ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
Error: ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
    at Object.fs.accessSync (fs.js:301:11)
    at new TransifexConfig (/home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-config/index.js:31:8)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-loader/dist/transifex-loader.js:134:21
    at Generator.next (<anonymous>)
    at step (/home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
 @ ./src/background/index.js 5:0-41

ERROR in ./_locales/es_MX/messages.json
ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
Error: ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
    at Object.fs.accessSync (fs.js:301:11)
    at new TransifexConfig (/home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-config/index.js:31:8)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-loader/dist/transifex-loader.js:134:21
    at Generator.next (<anonymous>)
    at step (/home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
 @ ./src/background/index.js 7:0-44

ERROR in ./_locales/fr/messages.json
ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
Error: ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
    at Object.fs.accessSync (fs.js:301:11)
    at new TransifexConfig (/home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-config/index.js:31:8)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-loader/dist/transifex-loader.js:134:21
    at Generator.next (<anonymous>)
    at step (/home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
 @ ./src/background/index.js 8:0-41

ERROR in ./_locales/en/messages.json
ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
Error: ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
    at Object.fs.accessSync (fs.js:301:11)
    at new TransifexConfig (/home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-config/index.js:31:8)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-loader/dist/transifex-loader.js:134:21
    at Generator.next (<anonymous>)
    at step (/home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
 @ ./src/background/index.js 6:0-41

ERROR in ./_locales/ru/messages.json
ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
Error: ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
    at Object.fs.accessSync (fs.js:301:11)
    at new TransifexConfig (/home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-config/index.js:31:8)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-loader/dist/transifex-loader.js:134:21
    at Generator.next (<anonymous>)
    at step (/home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
 @ ./src/background/index.js 10:0-41

ERROR in ./_locales/hr/messages.json
ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
Error: ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
    at Object.fs.accessSync (fs.js:301:11)
    at new TransifexConfig (/home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-config/index.js:31:8)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-loader/dist/transifex-loader.js:134:21
    at Generator.next (<anonymous>)
    at step (/home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
 @ ./src/background/index.js 9:0-41

ERROR in ./_locales/uk_UA/messages.json
ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
Error: ENOENT: no such file or directory, access '/home/maekclena/.tx/config'
    at Object.fs.accessSync (fs.js:301:11)
    at new TransifexConfig (/home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-config/index.js:31:8)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/transifex-loader/dist/transifex-loader.js:134:21
    at Generator.next (<anonymous>)
    at step (/home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/maekclena/Documents/justintv-stream-notifications/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
 @ ./src/background/index.js 11:0-44
```

**Comment by freaktechnik** [comment]
It is related to you not having a .transifexrc in your dev directory. But it is also related to that error, but it would still fail. Further currently the project does not work due to other reasons. I'm working on a major rewrite to how queueing and providers work.

**Comment by freaktechnik** [comment]
As a workaround you may want to remove the transifex-loader from the webpack config.

**Comment by freaktechnik** [comment]
This should be fixed now, please try again.

**Comment by maekclena** [comment]
The project builds and loads properly now.
